version: '2'
services:
  #
  # Fuseki
  #   No configuration needed
  #
  fuseki:
    container_name: fuseki
    image: stain/jena-fuseki
    volumes:
      - /fuseki # To persist datasets across restarts in /data/fuseki folder
    ports:
      - 3030:3030
    logging:
      options:
        max-size: 50m
    environment:
      - ADMIN_PASSWORD=some-secret

  #
  # MongoDB
  #   No configuration needed
  #
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    logging:
      options:
        max-size: 50m
    volumes:
      - /mongo # To persist datasets across restarts in /data/fuseki folder

  #
  # Solr
  #   - Before starting up the image, change ownership of the folder contaning the configset to uid:gid 8983:8983.
  #     E.g. $ chown -R 8983:8983 /path/to/andruian_configset
  #
  #
  solr:
    container_name: solr
    image: melkamar/solr-indexer
    ports:
      - 8983:8983
    logging:
      options:
        max-size: 50m
    volumes:
      - /opt/solr/server/solr/mycores
  #
  # Indexer
  #   - First volume mount should point to folder containing the indexer JAR and config files
  #
  indexer:
    container_name: indexer
    image: melkamar/indexer
    depends_on:
      - solr
      - mongo
      - fuseki
    ports:
      - 8080:8080
    logging:
      options:
        max-size: 50m
    volumes:
      - /indexer/logs
    # To provide custom application.properties, mount it using the following:
    #  - /path/to/application.properties:/indexer/application.properties
